Updated interfaces to easy creating
ARMmbed/easy-connect pull request #101
Opened 2018-06-20 09:11 UTC by AnttiKauppila

- Code is organized a bit better way
 * Connectivity logging is moved to own function
 * Connectivity setup is moved to own function

- Readme updated according to changes done

2018-06-29 06:59 UTC, JanneKiiskila requested changes

2018-06-29 06:59 UTC, JanneKiiskila commented on README.md
> +            "easy-connect.wifi-type": "\"ESP8266\"",
Seems like duplication that you have to tell it so many times, it's ESP8266? Doesn't seem right to me. One selection MUST be enough and then rest of it needs to happen outside of the `mbed_app.json`.

2018-06-29 06:59 UTC, JanneKiiskila commented on mcr20a-rf-driver.lib
> +https://github.com/ARMmbed/mcr20a-rf-driver/#17c467b64ab604887fc160cbe4118a51477e334b
The .lib changes should have been in another PR, IMHO.

2018-06-29 06:59 UTC, JanneKiiskila commented on mbed_lib.json
> +        "network-interface-name": {
This is too much repetition,  IMHO.

2018-07-02 12:36 UTC, AnttiKauppila commented
@JanneKiiskila Cleaned up the configuration as you suggested, please re-review

2018-08-17 08:03 UTC, closed without merging