Add ODIN WiFi support
ARMmbed/easy-connect pull request #4
Opened 2016-12-21 11:07 UTC by janjongboom

@jankii01

2016-12-21 14:56 UTC, JanneKiiskila requested changes

2016-12-21 14:56 UTC, jankii01 commented on easy-connect.h
> +    connect_success = esp.connect(MBED_CONF_APP_WIFI_SSID, MBED_CONF_APP_WIFI_PASSWORD);
This will fail on ODIN, you must set the security mode on ODIN.

2016-12-21 16:58 UTC, JanneKiiskila commented on easy-connect.h
> +    connect_success = esp.connect(MBED_CONF_APP_WIFI_SSID, MBED_CONF_APP_WIFI_PASSWORD);
Sorry, meant the wifi.connect a few lines below. It HAS to ahve the 3rd parameter - security, otherwise it just fails.

2016-12-21 16:58 UTC, jankii01 commented on easy-connect.h
> +    connect_success = wifi.connect(MBED_CONF_APP_WIFI_SSID, MBED_CONF_APP_WIFI_PASSWORD);
Here, security is needed.

2016-12-23 09:17 UTC, janjongboom commented
@jankii01 Fixed

2016-12-23 09:34 UTC, jankii01 commented on README.md
> +        "esp8266-debug": {
Why do we want to have this here?

2016-12-28 09:32 UTC, janjongboom commented on README.md
> +        "esp8266-debug": {
It enables tracing of the AT commands of the module, very useful for debugging. It has to be configured in the constructor, so this is a quick way of communicating from app -> the esp8266 driver.

2017-02-06 14:39 UTC, janjongboom commented
@JanneKiiskila ping. I don't have an ODIN board. Does this look sane?

2017-02-06 14:49 UTC, JanneKiiskila commented
A good test is worth a thousand expert opinions...

2017-02-06 18:51 UTC, JanneKiiskila commented on easy-connect.h
> +    connect_success = esp.connect(MBED_CONF_APP_WIFI_SSID, MBED_CONF_APP_WIFI_PASSWORD);
If we really want to tweak the codelines down, we could use one common wifi.connect and always give the 3 parameters. That works also with the esp8266.

2017-02-07 14:58 UTC, janjongboom commented
Superseded by #11

2017-02-07 14:58 UTC, closed without merging