Adapt to latest version of `wifi-x-nucleo-idw01m1`
ARMmbed/easy-connect pull request #45
Opened 2017-10-03 11:42 UTC by betzw

2017-10-05 12:53 UTC, JanneKiiskila commented
@betzw - ready yet? The hash is a bit old for the actual driver.
Plus I'd want to fix the AT-parser hash, we try to get the builds to be 100% repeatable, so that we know exactly which version came when.

2017-10-05 12:53 UTC, JanneKiiskila requested changes

2017-10-05 12:53 UTC, JanneKiiskila commented on ATParser.lib
> +https://github.com/ARMmbed/ATParser/
Fixed hash please for 100% reproducibility on builds.

2017-10-05 12:54 UTC, JanneKiiskila commented on stm-spirit1-rf-driver.lib
> +https://github.com/ARMmbed/stm-spirit1-rf-driver/
Same here.

2017-10-05 12:54 UTC, JanneKiiskila requested changes

2017-10-05 12:54 UTC, JanneKiiskila commented on wifi-x-nucleo-idw01m1.lib
> +https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/
And here. https://github.com/ARMmbed/easy-connect/pull/46

2017-10-05 13:44 UTC, betzw commented
Well, I hoped to be allowed to do so in order to get rid of having to continuously update SHA-1 hashes ... :tired_face: 
Do you think that I can get this _permission_  - at least with respect to my repos?

2017-10-09 09:10 UTC, betzw commented
@JanneKiiskila, pls. let me know.

2017-10-10 07:27 UTC, JanneKiiskila commented
How often do you think the hashes will really change? Problem being the repeatability of the releases, we do get results on different days if we don't use the hashes. So, for any official stuff - the hashes are pretty much a must, I'm afraid.

2017-10-10 08:22 UTC, betzw commented
OK, will update asap!

2017-10-10 09:11 UTC, JanneKiiskila commented
Thanks. I've almost done the pull finalization for the mbed-os-example-client repo, so I could update the hash to match this one as well on the same go.

2017-10-10 13:31 UTC, betzw commented
Updated.

2017-10-10 13:33 UTC, JanneKiiskila approved these changes

2017-10-10 13:33 UTC, merged